import type { CareerDefinition } from './types';
import {
  BARISTA_ACTIONS,
  CONSULTING_ACTIONS,
  ENGINEER_ACTIONS,
  FINANCE_ACTIONS,
  FULL_TIME_ACTIONS,
  HEALTHCARE_ACTIONS,
  LEGAL_ACTIONS,
  NURSE_ACTIONS,
  RETAIL_ACTIONS,
  TRADES_ACTIONS,
} from './actions';

export const fullTimeCareers: CareerDefinition[] = [
  {
    id: 'full_time_logistics_coordinator',
    title: 'Logistics Coordinator',
    company: 'QuickDrop',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 20,
    salary: 54800,
    requiredExperience: 2,
    stress: 40,
    prestige: 36,
    coworkerCountRange: { min: 10, max: 28 },
    coworkerRoles: ['Dispatcher', 'Coordinator', 'Operations Manager'],
    compensation: {
      bonusRate: 0.06,
      tipsPerYear: 800,
      overtimeHours: 36,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_operations_manager'],
      minYearsInRole: 2,
      minPerformance: 68,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Coordinate routes, staffing, and service performance.',
  },
  {
    id: 'full_time_cafe_manager',
    title: 'Cafe Manager',
    company: 'Corner Brew',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 20,
    salary: 51200,
    requiredExperience: 2,
    stress: 44,
    prestige: 33,
    coworkerCountRange: { min: 8, max: 24 },
    coworkerRoles: ['Barista', 'Shift Lead', 'Manager'],
    compensation: {
      bonusRate: 0.05,
      tipsPerYear: 4500,
      overtimeHours: 36,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_operations_manager'],
      minYearsInRole: 2,
      minPerformance: 70,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Own staffing, inventory, and customer experience outcomes.',
  },
  {
    id: 'full_time_operations_manager',
    title: 'Operations Manager',
    company: 'Corner Brew Group',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 71600,
    requiredExperience: 4,
    stress: 50,
    prestige: 45,
    coworkerCountRange: { min: 14, max: 34 },
    coworkerRoles: ['Store Manager', 'Ops Manager', 'Regional Director'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 1500,
      overtimeHours: 40,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_district_cafe_manager'],
      minYearsInRole: 2,
      minPerformance: 74,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Run multi-site operations and improve team execution.',
  },
  {
    id: 'full_time_district_cafe_manager',
    title: 'District Cafe Manager',
    company: 'Corner Brew',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 74800,
    requiredExperience: 4,
    stress: 52,
    prestige: 48,
    coworkerCountRange: { min: 14, max: 38 },
    coworkerRoles: ['Store Manager', 'District Manager', 'Regional Director'],
    compensation: {
      bonusRate: 0.09,
      tipsPerYear: 3600,
      overtimeHours: 42,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_regional_service_director'],
      minYearsInRole: 3,
      minPerformance: 80,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Lead multiple locations and mentor store leadership teams.',
  },
  {
    id: 'full_time_regional_service_director',
    title: 'Regional Service Director',
    company: 'Corner Brew Group',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 104000,
    requiredExperience: 7,
    stress: 58,
    prestige: 62,
    coworkerCountRange: { min: 18, max: 50 },
    coworkerRoles: ['District Manager', 'Regional Director', 'VP Operations'],
    compensation: {
      bonusRate: 0.14,
      tipsPerYear: 0,
      overtimeHours: 46,
      overtimeMultiplier: 1.35,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Set regional strategy and scale operational standards.',
  },
  {
    id: 'full_time_junior_accountant',
    title: 'Junior Accountant',
    company: 'Blue Ledger LLP',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 20,
    salary: 54000,
    requiredExperience: 1,
    stress: 42,
    prestige: 43,
    coworkerCountRange: { min: 8, max: 24 },
    coworkerRoles: ['Accountant', 'Analyst', 'Senior Accountant'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 0,
      overtimeHours: 50,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_senior_accountant'],
      minYearsInRole: 2,
      minPerformance: 68,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Steady office role with clear promotion ladders.',
  },
  {
    id: 'full_time_senior_accountant',
    title: 'Senior Accountant',
    company: 'Blue Ledger LLP',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 86400,
    requiredExperience: 4,
    stress: 50,
    prestige: 54,
    coworkerCountRange: { min: 10, max: 30 },
    coworkerRoles: ['Accountant', 'Senior Accountant', 'Finance Manager'],
    compensation: {
      bonusRate: 0.12,
      tipsPerYear: 0,
      overtimeHours: 60,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_finance_manager'],
      minYearsInRole: 3,
      minPerformance: 76,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Lead reporting cycles and shape financial operations.',
  },
  {
    id: 'full_time_finance_manager',
    title: 'Finance Manager',
    company: 'Blue Ledger LLP',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 121000,
    requiredExperience: 7,
    stress: 60,
    prestige: 68,
    coworkerCountRange: { min: 12, max: 34 },
    coworkerRoles: ['Senior Accountant', 'Finance Manager', 'Controller'],
    compensation: {
      bonusRate: 0.17,
      tipsPerYear: 0,
      overtimeHours: 68,
      overtimeMultiplier: 1.4,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Own forecasting, budgeting, and financial strategy.',
  },
  {
    id: 'full_time_registered_nurse',
    title: 'Registered Nurse',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 22,
    salary: 73600,
    requiredExperience: 2,
    requiredEducation: 'bachelors',
    stress: 58,
    prestige: 62,
    coworkerCountRange: { min: 12, max: 40 },
    coworkerRoles: ['RN', 'Charge Nurse', 'Physician'],
    compensation: {
      bonusRate: 0.07,
      tipsPerYear: 0,
      overtimeHours: 80,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_charge_nurse'],
      minYearsInRole: 2,
      minPerformance: 70,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'High-impact care work with strong long-term demand.',
  },
  {
    id: 'full_time_charge_nurse',
    title: 'Charge Nurse',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 25,
    salary: 96800,
    requiredExperience: 4,
    requiredEducation: 'bachelors',
    stress: 66,
    prestige: 72,
    coworkerCountRange: { min: 14, max: 48 },
    coworkerRoles: ['RN', 'Charge Nurse', 'Nurse Manager'],
    compensation: {
      bonusRate: 0.1,
      tipsPerYear: 0,
      overtimeHours: 90,
      overtimeMultiplier: 1.45,
    },
    progression: {
      nextJobIds: ['full_time_nurse_manager'],
      minYearsInRole: 3,
      minPerformance: 79,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'Lead the floor team and drive patient care quality.',
  },
  {
    id: 'full_time_nurse_manager',
    title: 'Nurse Manager',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 29,
    salary: 124000,
    requiredExperience: 8,
    requiredEducation: 'bachelors',
    stress: 70,
    prestige: 80,
    coworkerCountRange: { min: 18, max: 56 },
    coworkerRoles: ['Charge Nurse', 'Nurse Manager', 'Clinical Director'],
    compensation: {
      bonusRate: 0.16,
      tipsPerYear: 0,
      overtimeHours: 92,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'Lead nursing operations and clinical workforce planning.',
  },
  {
    id: 'full_time_software_engineer',
    title: 'Software Engineer',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 21,
    salary: 92000,
    requiredExperience: 2,
    requiredEducation: 'bachelors',
    stress: 48,
    prestige: 68,
    coworkerCountRange: { min: 6, max: 26 },
    coworkerRoles: ['Software Engineer', 'Product Manager', 'Tech Lead'],
    compensation: {
      bonusRate: 0.12,
      tipsPerYear: 0,
      overtimeHours: 60,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_senior_software_engineer'],
      minYearsInRole: 2,
      minPerformance: 72,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Build products, ship features, and earn high compensation.',
  },
  {
    id: 'full_time_senior_software_engineer',
    title: 'Senior Software Engineer',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 138000,
    requiredExperience: 5,
    requiredEducation: 'bachelors',
    stress: 56,
    prestige: 78,
    coworkerCountRange: { min: 8, max: 34 },
    coworkerRoles: ['Senior Engineer', 'Tech Lead', 'Engineering Manager'],
    compensation: {
      bonusRate: 0.16,
      tipsPerYear: 0,
      overtimeHours: 70,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_principal_engineer'],
      minYearsInRole: 3,
      minPerformance: 82,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Own architecture and mentor teams on critical delivery.',
  },
  {
    id: 'full_time_principal_engineer',
    title: 'Principal Engineer',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 29,
    salary: 198000,
    requiredExperience: 9,
    requiredEducation: 'bachelors',
    stress: 62,
    prestige: 90,
    coworkerCountRange: { min: 12, max: 40 },
    coworkerRoles: ['Tech Lead', 'Principal Engineer', 'Engineering Director'],
    compensation: {
      bonusRate: 0.22,
      tipsPerYear: 0,
      overtimeHours: 74,
      overtimeMultiplier: 1.35,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Drive architecture strategy across multiple engineering teams.',
  },
  {
    id: 'full_time_trades_apprentice',
    title: 'Electrical Apprentice',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 18,
    salary: 49600,
    requiredExperience: 0,
    stress: 35,
    prestige: 40,
    coworkerCountRange: { min: 5, max: 18 },
    coworkerRoles: ['Apprentice', 'Journeyman', 'Foreman'],
    compensation: {
      bonusRate: 0.05,
      tipsPerYear: 0,
      overtimeHours: 70,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_journeyman_electrician'],
      minYearsInRole: 2,
      minPerformance: 66,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Hands-on career path with strong upside over time.',
  },
  {
    id: 'full_time_journeyman_electrician',
    title: 'Journeyman Electrician',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 21,
    salary: 78200,
    requiredExperience: 3,
    stress: 45,
    prestige: 56,
    coworkerCountRange: { min: 6, max: 20 },
    coworkerRoles: ['Journeyman', 'Foreman', 'Project Manager'],
    compensation: {
      bonusRate: 0.09,
      tipsPerYear: 0,
      overtimeHours: 95,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_master_electrician'],
      minYearsInRole: 3,
      minPerformance: 75,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Run major installs and train incoming apprentices.',
  },
  {
    id: 'full_time_master_electrician',
    title: 'Master Electrician',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 27,
    salary: 116000,
    requiredExperience: 8,
    stress: 54,
    prestige: 70,
    coworkerCountRange: { min: 8, max: 26 },
    coworkerRoles: ['Foreman', 'Master Electrician', 'Project Superintendent'],
    compensation: {
      bonusRate: 0.14,
      tipsPerYear: 0,
      overtimeHours: 102,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Lead critical projects and certify high-risk electrical work.',
  },
  {
    id: 'full_time_legal_aide',
    title: 'Legal Aide',
    company: 'County Office',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 22,
    salary: 59200,
    requiredExperience: 1,
    requiredEducation: 'bachelors',
    stress: 48,
    prestige: 44,
    coworkerCountRange: { min: 10, max: 26 },
    coworkerRoles: ['Paralegal', 'Legal Aide', 'Assistant Defender'],
    compensation: {
      bonusRate: 0.06,
      tipsPerYear: 0,
      overtimeHours: 58,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_public_defender'],
      minYearsInRole: 2,
      minPerformance: 70,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Support public defense teams with case and court preparation.',
  },
  {
    id: 'full_time_public_defender',
    title: 'Public Defender',
    company: 'County Office',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 25,
    salary: 81500,
    requiredExperience: 3,
    requiredEducation: 'doctorate',
    stress: 70,
    prestige: 75,
    coworkerCountRange: { min: 10, max: 28 },
    coworkerRoles: ['Attorney', 'Investigator', 'Court Clerk'],
    compensation: {
      bonusRate: 0.1,
      tipsPerYear: 0,
      overtimeHours: 110,
      overtimeMultiplier: 1.45,
    },
    progression: {
      nextJobIds: ['full_time_senior_public_defender'],
      minYearsInRole: 3,
      minPerformance: 80,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Mission-heavy legal work with intense responsibility.',
  },
  {
    id: 'full_time_senior_public_defender',
    title: 'Senior Public Defender',
    company: 'County Office',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 30,
    salary: 138000,
    requiredExperience: 9,
    requiredEducation: 'doctorate',
    stress: 78,
    prestige: 88,
    coworkerCountRange: { min: 14, max: 34 },
    coworkerRoles: ['Attorney', 'Senior Defender', 'Chief Defender'],
    compensation: {
      bonusRate: 0.16,
      tipsPerYear: 0,
      overtimeHours: 118,
      overtimeMultiplier: 1.5,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Lead high-impact defense strategy and mentor legal teams.',
  },
  {
    id: 'full_time_investment_banker',
    title: 'Investment Banker',
    company: 'Meridian Capital',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 185000,
    requiredExperience: 2,
    requiredEducation: 'bachelors',
    stress: 72,
    prestige: 88,
    coworkerCountRange: { min: 12, max: 40 },
    coworkerRoles: ['Analyst', 'Associate', 'VP'],
    compensation: {
      bonusRate: 0.35,
      tipsPerYear: 0,
      overtimeHours: 120,
      overtimeMultiplier: 1.5,
    },
    progression: {
      nextJobIds: ['full_time_vp_investment_banking'],
      minYearsInRole: 3,
      minPerformance: 85,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'High-stakes M&A and capital markets with intense hours and high compensation.',
  },
  {
    id: 'full_time_vp_investment_banking',
    title: 'VP Investment Banking',
    company: 'Meridian Capital',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 30,
    salary: 320000,
    requiredExperience: 7,
    requiredEducation: 'bachelors',
    stress: 78,
    prestige: 92,
    coworkerCountRange: { min: 16, max: 50 },
    coworkerRoles: ['VP', 'Director', 'Managing Director'],
    compensation: {
      bonusRate: 0.45,
      tipsPerYear: 0,
      overtimeHours: 130,
      overtimeMultiplier: 1.5,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Lead deal execution and client relationships in high-stakes transactions.',
  },
  {
    id: 'full_time_private_equity_associate',
    title: 'Private Equity Associate',
    company: 'Crestwood Partners',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 26,
    salary: 220000,
    requiredExperience: 3,
    requiredEducation: 'bachelors',
    stress: 70,
    prestige: 90,
    coworkerCountRange: { min: 8, max: 28 },
    coworkerRoles: ['Associate', 'Principal', 'Partner'],
    compensation: {
      bonusRate: 0.4,
      tipsPerYear: 0,
      overtimeHours: 110,
      overtimeMultiplier: 1.5,
    },
    progression: {
      nextJobIds: ['full_time_pe_principal'],
      minYearsInRole: 4,
      minPerformance: 88,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Deal sourcing, due diligence, and portfolio company value creation.',
  },
  {
    id: 'full_time_pe_principal',
    title: 'PE Principal',
    company: 'Crestwood Partners',
    category: 'finance',
    track: 'fullTime',
    path: 'standard',
    minAge: 32,
    salary: 450000,
    requiredExperience: 9,
    requiredEducation: 'bachelors',
    stress: 75,
    prestige: 95,
    coworkerCountRange: { min: 10, max: 32 },
    coworkerRoles: ['Principal', 'Partner', 'Managing Partner'],
    compensation: {
      bonusRate: 0.55,
      tipsPerYear: 0,
      overtimeHours: 125,
      overtimeMultiplier: 1.5,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...FINANCE_ACTIONS],
    summary: 'Lead investment decisions and portfolio strategy at a top-tier fund.',
  },
  {
    id: 'full_time_surgeon',
    title: 'Surgeon',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 32,
    salary: 485000,
    requiredExperience: 10,
    requiredEducation: 'doctorate',
    stress: 85,
    prestige: 95,
    coworkerCountRange: { min: 20, max: 60 },
    coworkerRoles: ['Resident', 'Attending', 'Chief'],
    compensation: {
      bonusRate: 0.18,
      tipsPerYear: 0,
      overtimeHours: 140,
      overtimeMultiplier: 1.6,
    },
    progression: {
      nextJobIds: ['full_time_chief_surgeon'],
      minYearsInRole: 5,
      minPerformance: 90,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'High-stakes surgical practice with life-and-death responsibility.',
  },
  {
    id: 'full_time_chief_surgeon',
    title: 'Chief of Surgery',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 38,
    salary: 620000,
    requiredExperience: 15,
    requiredEducation: 'doctorate',
    stress: 88,
    prestige: 98,
    coworkerCountRange: { min: 25, max: 80 },
    coworkerRoles: ['Attending', 'Chief', 'Administrator'],
    compensation: {
      bonusRate: 0.22,
      tipsPerYear: 0,
      overtimeHours: 150,
      overtimeMultiplier: 1.6,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'Lead surgical department strategy and mentor the next generation.',
  },
  {
    id: 'full_time_physician_assistant',
    title: 'Physician Assistant',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 112000,
    requiredExperience: 2,
    requiredEducation: 'masters',
    stress: 62,
    prestige: 68,
    coworkerCountRange: { min: 14, max: 42 },
    coworkerRoles: ['PA', 'NP', 'Physician'],
    compensation: {
      bonusRate: 0.09,
      tipsPerYear: 0,
      overtimeHours: 85,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_senior_pa'],
      minYearsInRole: 3,
      minPerformance: 75,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'Clinical care with autonomy and strong compensation.',
  },
  {
    id: 'full_time_senior_pa',
    title: 'Senior PA',
    company: 'Metro General',
    category: 'healthcare',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 148000,
    requiredExperience: 6,
    requiredEducation: 'masters',
    stress: 68,
    prestige: 75,
    coworkerCountRange: { min: 16, max: 48 },
    coworkerRoles: ['PA', 'Senior PA', 'Clinical Lead'],
    compensation: {
      bonusRate: 0.12,
      tipsPerYear: 0,
      overtimeHours: 95,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...NURSE_ACTIONS, ...HEALTHCARE_ACTIONS],
    summary: 'Lead PA role with expanded clinical responsibilities.',
  },
  {
    id: 'full_time_tech_lead',
    title: 'Tech Lead',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 27,
    salary: 168000,
    requiredExperience: 6,
    requiredEducation: 'bachelors',
    stress: 60,
    prestige: 82,
    coworkerCountRange: { min: 10, max: 38 },
    coworkerRoles: ['Engineer', 'Tech Lead', 'Engineering Manager'],
    compensation: {
      bonusRate: 0.18,
      tipsPerYear: 0,
      overtimeHours: 75,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_engineering_manager'],
      minYearsInRole: 2,
      minPerformance: 80,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Lead technical direction and mentor engineers on critical systems.',
  },
  {
    id: 'full_time_engineering_manager',
    title: 'Engineering Manager',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 30,
    salary: 228000,
    requiredExperience: 9,
    requiredEducation: 'bachelors',
    stress: 66,
    prestige: 86,
    coworkerCountRange: { min: 14, max: 44 },
    coworkerRoles: ['Tech Lead', 'Manager', 'Director'],
    compensation: {
      bonusRate: 0.24,
      tipsPerYear: 0,
      overtimeHours: 80,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_director_engineering'],
      minYearsInRole: 3,
      minPerformance: 84,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Manage engineering teams and drive product delivery.',
  },
  {
    id: 'full_time_director_engineering',
    title: 'Director of Engineering',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 34,
    salary: 295000,
    requiredExperience: 12,
    requiredEducation: 'bachelors',
    stress: 70,
    prestige: 92,
    coworkerCountRange: { min: 18, max: 56 },
    coworkerRoles: ['Manager', 'Director', 'VP Engineering'],
    compensation: {
      bonusRate: 0.3,
      tipsPerYear: 0,
      overtimeHours: 85,
      overtimeMultiplier: 1.35,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...ENGINEER_ACTIONS],
    summary: 'Lead multiple engineering teams and set technical strategy.',
  },
  {
    id: 'full_time_product_manager',
    title: 'Product Manager',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 25,
    salary: 142000,
    requiredExperience: 3,
    requiredEducation: 'bachelors',
    stress: 58,
    prestige: 76,
    coworkerCountRange: { min: 8, max: 32 },
    coworkerRoles: ['PM', 'Senior PM', 'Director'],
    compensation: {
      bonusRate: 0.16,
      tipsPerYear: 0,
      overtimeHours: 65,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_senior_pm'],
      minYearsInRole: 2,
      minPerformance: 75,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Own product strategy and coordinate cross-functional delivery.',
  },
  {
    id: 'full_time_senior_pm',
    title: 'Senior Product Manager',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 29,
    salary: 198000,
    requiredExperience: 7,
    requiredEducation: 'bachelors',
    stress: 64,
    prestige: 84,
    coworkerCountRange: { min: 12, max: 40 },
    coworkerRoles: ['PM', 'Senior PM', 'Director'],
    compensation: {
      bonusRate: 0.22,
      tipsPerYear: 0,
      overtimeHours: 70,
      overtimeMultiplier: 1.35,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Lead product strategy for major product lines.',
  },
  {
    id: 'full_time_data_scientist',
    title: 'Data Scientist',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 138000,
    requiredExperience: 2,
    requiredEducation: 'masters',
    stress: 52,
    prestige: 74,
    coworkerCountRange: { min: 6, max: 24 },
    coworkerRoles: ['Data Scientist', 'ML Engineer', 'Data Lead'],
    compensation: {
      bonusRate: 0.14,
      tipsPerYear: 0,
      overtimeHours: 60,
      overtimeMultiplier: 1.35,
    },
    progression: {
      nextJobIds: ['full_time_senior_data_scientist'],
      minYearsInRole: 2,
      minPerformance: 72,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Build ML models and drive data-driven decision making.',
  },
  {
    id: 'full_time_senior_data_scientist',
    title: 'Senior Data Scientist',
    company: 'Northstar Systems',
    category: 'tech',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 188000,
    requiredExperience: 6,
    requiredEducation: 'masters',
    stress: 58,
    prestige: 82,
    coworkerCountRange: { min: 8, max: 30 },
    coworkerRoles: ['Data Scientist', 'Senior DS', 'Data Lead'],
    compensation: {
      bonusRate: 0.2,
      tipsPerYear: 0,
      overtimeHours: 65,
      overtimeMultiplier: 1.35,
    },
    jobActions: FULL_TIME_ACTIONS,
    summary: 'Lead ML initiatives and mentor data science teams.',
  },
  {
    id: 'full_time_corporate_lawyer',
    title: 'Corporate Lawyer',
    company: 'Chambers Legal Group',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 26,
    salary: 195000,
    requiredExperience: 2,
    requiredEducation: 'doctorate',
    stress: 68,
    prestige: 85,
    coworkerCountRange: { min: 12, max: 36 },
    coworkerRoles: ['Associate', 'Partner', 'Managing Partner'],
    compensation: {
      bonusRate: 0.25,
      tipsPerYear: 0,
      overtimeHours: 100,
      overtimeMultiplier: 1.45,
    },
    progression: {
      nextJobIds: ['full_time_partner_corporate'],
      minYearsInRole: 6,
      minPerformance: 88,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Handle M&A, securities, and complex corporate transactions.',
  },
  {
    id: 'full_time_partner_corporate',
    title: 'Corporate Partner',
    company: 'Chambers Legal Group',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 34,
    salary: 485000,
    requiredExperience: 10,
    requiredEducation: 'doctorate',
    stress: 74,
    prestige: 94,
    coworkerCountRange: { min: 16, max: 48 },
    coworkerRoles: ['Partner', 'Senior Partner', 'Managing Partner'],
    compensation: {
      bonusRate: 0.4,
      tipsPerYear: 0,
      overtimeHours: 110,
      overtimeMultiplier: 1.5,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Lead major deals and build client relationships at a top firm.',
  },
  {
    id: 'full_time_litigation_attorney',
    title: 'Litigation Attorney',
    company: 'Chambers Legal Group',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 26,
    salary: 182000,
    requiredExperience: 2,
    requiredEducation: 'doctorate',
    stress: 70,
    prestige: 83,
    coworkerCountRange: { min: 10, max: 32 },
    coworkerRoles: ['Associate', 'Partner', 'Trial Lead'],
    compensation: {
      bonusRate: 0.24,
      tipsPerYear: 0,
      overtimeHours: 105,
      overtimeMultiplier: 1.45,
    },
    progression: {
      nextJobIds: ['full_time_partner_litigation'],
      minYearsInRole: 7,
      minPerformance: 86,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'High-stakes trial work with intense preparation and court time.',
  },
  {
    id: 'full_time_partner_litigation',
    title: 'Litigation Partner',
    company: 'Chambers Legal Group',
    category: 'legal',
    track: 'fullTime',
    path: 'standard',
    minAge: 35,
    salary: 520000,
    requiredExperience: 11,
    requiredEducation: 'doctorate',
    stress: 76,
    prestige: 95,
    coworkerCountRange: { min: 14, max: 42 },
    coworkerRoles: ['Partner', 'Senior Partner', 'Managing Partner'],
    compensation: {
      bonusRate: 0.42,
      tipsPerYear: 0,
      overtimeHours: 115,
      overtimeMultiplier: 1.5,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...LEGAL_ACTIONS],
    summary: 'Lead complex litigation and mentor trial attorneys.',
  },
  {
    id: 'full_time_plumber',
    title: 'Master Plumber',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 25,
    salary: 84200,
    requiredExperience: 5,
    stress: 48,
    prestige: 58,
    coworkerCountRange: { min: 6, max: 20 },
    coworkerRoles: ['Apprentice', 'Journeyman', 'Foreman'],
    compensation: {
      bonusRate: 0.1,
      tipsPerYear: 0,
      overtimeHours: 88,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_plumbing_foreman'],
      minYearsInRole: 3,
      minPerformance: 72,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Skilled plumbing work with strong demand and good pay.',
  },
  {
    id: 'full_time_plumbing_foreman',
    title: 'Plumbing Foreman',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 30,
    salary: 118000,
    requiredExperience: 9,
    stress: 56,
    prestige: 68,
    coworkerCountRange: { min: 8, max: 26 },
    coworkerRoles: ['Master Plumber', 'Foreman', 'Superintendent'],
    compensation: {
      bonusRate: 0.15,
      tipsPerYear: 0,
      overtimeHours: 95,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Lead plumbing crews on major commercial projects.',
  },
  {
    id: 'full_time_hvac_technician',
    title: 'HVAC Technician',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 22,
    salary: 76800,
    requiredExperience: 3,
    stress: 44,
    prestige: 54,
    coworkerCountRange: { min: 5, max: 18 },
    coworkerRoles: ['Apprentice', 'Technician', 'Lead Tech'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 0,
      overtimeHours: 82,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_hvac_lead'],
      minYearsInRole: 3,
      minPerformance: 70,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Install and maintain heating and cooling systems.',
  },
  {
    id: 'full_time_hvac_lead',
    title: 'HVAC Lead Technician',
    company: 'Prime Volt Co.',
    category: 'trades',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 108000,
    requiredExperience: 8,
    stress: 52,
    prestige: 64,
    coworkerCountRange: { min: 7, max: 22 },
    coworkerRoles: ['Technician', 'Lead Tech', 'Supervisor'],
    compensation: {
      bonusRate: 0.13,
      tipsPerYear: 0,
      overtimeHours: 90,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...TRADES_ACTIONS],
    summary: 'Lead HVAC teams and handle complex commercial systems.',
  },
  {
    id: 'full_time_retail_store_manager',
    title: 'Store Manager',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 68200,
    requiredExperience: 4,
    stress: 52,
    prestige: 48,
    coworkerCountRange: { min: 12, max: 32 },
    coworkerRoles: ['Associate', 'Supervisor', 'District Manager'],
    compensation: {
      bonusRate: 0.1,
      tipsPerYear: 0,
      overtimeHours: 50,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_district_manager_retail'],
      minYearsInRole: 2,
      minPerformance: 74,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...RETAIL_ACTIONS],
    summary: 'Run store operations, staffing, and customer experience.',
  },
  {
    id: 'full_time_district_manager_retail',
    title: 'District Manager',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 112000,
    requiredExperience: 8,
    stress: 60,
    prestige: 62,
    coworkerCountRange: { min: 16, max: 44 },
    coworkerRoles: ['Store Manager', 'District Manager', 'Regional Director'],
    compensation: {
      bonusRate: 0.16,
      tipsPerYear: 0,
      overtimeHours: 58,
      overtimeMultiplier: 1.35,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...RETAIL_ACTIONS],
    summary: 'Oversee multiple stores and drive regional performance.',
  },
  {
    id: 'full_time_restaurant_manager',
    title: 'Restaurant Manager',
    company: 'Corner Brew',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 23,
    salary: 61200,
    requiredExperience: 3,
    stress: 56,
    prestige: 42,
    coworkerCountRange: { min: 10, max: 28 },
    coworkerRoles: ['Server', 'Shift Lead', 'General Manager'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 2400,
      overtimeHours: 48,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_gm_restaurant'],
      minYearsInRole: 2,
      minPerformance: 72,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Manage restaurant operations, staff, and customer experience.',
  },
  {
    id: 'full_time_gm_restaurant',
    title: 'General Manager',
    company: 'Corner Brew',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 27,
    salary: 94800,
    requiredExperience: 7,
    stress: 64,
    prestige: 58,
    coworkerCountRange: { min: 14, max: 36 },
    coworkerRoles: ['Manager', 'GM', 'Regional Manager'],
    compensation: {
      bonusRate: 0.14,
      tipsPerYear: 1800,
      overtimeHours: 54,
      overtimeMultiplier: 1.35,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Own P&L and strategic direction for a high-volume restaurant.',
  },
  {
    id: 'full_time_consultant',
    title: 'Management Consultant',
    company: 'Blue Ledger LLP',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 24,
    salary: 128000,
    requiredExperience: 2,
    requiredEducation: 'masters',
    stress: 66,
    prestige: 78,
    coworkerCountRange: { min: 8, max: 28 },
    coworkerRoles: ['Consultant', 'Senior Consultant', 'Principal'],
    compensation: {
      bonusRate: 0.18,
      tipsPerYear: 0,
      overtimeHours: 85,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_senior_consultant'],
      minYearsInRole: 2,
      minPerformance: 76,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...CONSULTING_ACTIONS],
    summary: 'Project-based consulting with high travel and client pressure.',
  },
  {
    id: 'full_time_senior_consultant',
    title: 'Senior Consultant',
    company: 'Blue Ledger LLP',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 28,
    salary: 198000,
    requiredExperience: 6,
    requiredEducation: 'masters',
    stress: 72,
    prestige: 86,
    coworkerCountRange: { min: 12, max: 36 },
    coworkerRoles: ['Consultant', 'Senior Consultant', 'Principal'],
    compensation: {
      bonusRate: 0.26,
      tipsPerYear: 0,
      overtimeHours: 95,
      overtimeMultiplier: 1.4,
    },
    progression: {
      nextJobIds: ['full_time_principal_consultant'],
      minYearsInRole: 4,
      minPerformance: 84,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...CONSULTING_ACTIONS],
    summary: 'Lead client engagements and develop junior consultants.',
  },
  {
    id: 'full_time_principal_consultant',
    title: 'Principal Consultant',
    company: 'Blue Ledger LLP',
    category: 'service',
    track: 'fullTime',
    path: 'standard',
    minAge: 34,
    salary: 285000,
    requiredExperience: 11,
    requiredEducation: 'masters',
    stress: 76,
    prestige: 92,
    coworkerCountRange: { min: 16, max: 48 },
    coworkerRoles: ['Senior Consultant', 'Principal', 'Partner'],
    compensation: {
      bonusRate: 0.35,
      tipsPerYear: 0,
      overtimeHours: 100,
      overtimeMultiplier: 1.45,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...CONSULTING_ACTIONS],
    summary: 'Own client relationships and drive firm strategy.',
  },
];
