import type { CareerDefinition } from './types';
import { BARISTA_ACTIONS, PART_TIME_ACTIONS } from './actions';

export const partTimeCareers: CareerDefinition[] = [
  {
    id: 'part_time_grocery_clerk',
    title: 'Grocery Clerk',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 18200,
    requiredExperience: 0,
    stress: 24,
    prestige: 12,
    coworkerCountRange: { min: 4, max: 12 },
    coworkerRoles: ['Cashier', 'Stocker', 'Shift Lead'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 20,
      overtimeMultiplier: 1.2,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Stock shelves, help customers, and learn day-to-day operations.',
  },
  {
    id: 'part_time_cafe_barista',
    title: 'Barista',
    company: 'Corner Brew',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 19600,
    requiredExperience: 0,
    stress: 28,
    prestige: 15,
    coworkerCountRange: { min: 3, max: 10 },
    coworkerRoles: ['Barista', 'Shift Lead', 'Store Manager'],
    compensation: {
      tipsPerYear: 2200,
      overtimeHours: 18,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['part_time_shift_lead_barista'],
      minYearsInRole: 1,
      minPerformance: 58,
    },
    jobActions: [...PART_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Fast shifts, people skills, and tip-based upside.',
  },
  {
    id: 'part_time_shift_lead_barista',
    title: 'Shift Lead Barista',
    company: 'Corner Brew',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 24400,
    requiredExperience: 1,
    stress: 34,
    prestige: 22,
    coworkerCountRange: { min: 5, max: 14 },
    coworkerRoles: ['Barista', 'Shift Lead', 'Assistant Manager'],
    compensation: {
      tipsPerYear: 3200,
      bonusRate: 0.03,
      overtimeHours: 24,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_cafe_manager'],
      minYearsInRole: 2,
      minPerformance: 65,
    },
    jobActions: [...PART_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Lead shifts, coach newer hires, and run store flow.',
  },
  {
    id: 'part_time_library_aide',
    title: 'Library Aide',
    company: 'City Library',
    category: 'education',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 17400,
    requiredExperience: 0,
    stress: 16,
    prestige: 18,
    coworkerCountRange: { min: 2, max: 8 },
    coworkerRoles: ['Aide', 'Librarian', 'Archivist'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 8,
      overtimeMultiplier: 1.15,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Low-noise work that boosts discipline and routine.',
  },
  {
    id: 'part_time_delivery_runner',
    title: 'Delivery Runner',
    company: 'QuickDrop',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 23100,
    requiredExperience: 0,
    stress: 32,
    prestige: 14,
    coworkerCountRange: { min: 5, max: 16 },
    coworkerRoles: ['Driver', 'Dispatcher', 'Route Lead'],
    compensation: {
      tipsPerYear: 1200,
      overtimeHours: 40,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['full_time_logistics_coordinator'],
      minYearsInRole: 1,
      minPerformance: 58,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Route-based work with flexible blocks and movement.',
  },
  {
    id: 'part_time_it_helpdesk',
    title: 'IT Helpdesk Assistant',
    company: 'Campus Tech Hub',
    category: 'tech',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 25200,
    requiredExperience: 1,
    stress: 26,
    prestige: 28,
    coworkerCountRange: { min: 4, max: 14 },
    coworkerRoles: ['Support Tech', 'Sysadmin', 'IT Lead'],
    compensation: {
      bonusRate: 0.05,
      tipsPerYear: 0,
      overtimeHours: 32,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_software_engineer'],
      minYearsInRole: 2,
      minPerformance: 67,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Practical support role that can launch a tech career.',
  },
  {
    id: 'part_time_retail_sales',
    title: 'Retail Sales Associate',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 20800,
    requiredExperience: 0,
    stress: 26,
    prestige: 14,
    coworkerCountRange: { min: 4, max: 14 },
    coworkerRoles: ['Cashier', 'Sales Associate', 'Shift Lead'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 22,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['part_time_shift_lead_retail'],
      minYearsInRole: 1,
      minPerformance: 60,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Customer service and sales in a retail environment.',
  },
  {
    id: 'part_time_shift_lead_retail',
    title: 'Shift Lead',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 25600,
    requiredExperience: 1,
    stress: 32,
    prestige: 20,
    coworkerCountRange: { min: 6, max: 16 },
    coworkerRoles: ['Sales Associate', 'Shift Lead', 'Assistant Manager'],
    compensation: {
      bonusRate: 0.04,
      tipsPerYear: 0,
      overtimeHours: 28,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_retail_store_manager'],
      minYearsInRole: 2,
      minPerformance: 68,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Lead shifts and handle customer escalations.',
  },
  {
    id: 'part_time_tutor',
    title: 'Tutor',
    company: 'Campus Tech Hub',
    category: 'education',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 22400,
    requiredExperience: 1,
    stress: 22,
    prestige: 24,
    coworkerCountRange: { min: 2, max: 10 },
    coworkerRoles: ['Tutor', 'Senior Tutor', 'Coordinator'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 12,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['part_time_senior_tutor'],
      minYearsInRole: 1,
      minPerformance: 65,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Help students with coursework and test prep.',
  },
  {
    id: 'part_time_senior_tutor',
    title: 'Senior Tutor',
    company: 'Campus Tech Hub',
    category: 'education',
    track: 'partTime',
    path: 'standard',
    minAge: 20,
    salary: 28800,
    requiredExperience: 2,
    stress: 28,
    prestige: 32,
    coworkerCountRange: { min: 3, max: 12 },
    coworkerRoles: ['Tutor', 'Senior Tutor', 'Coordinator'],
    compensation: {
      bonusRate: 0.05,
      tipsPerYear: 0,
      overtimeHours: 16,
      overtimeMultiplier: 1.25,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Lead tutoring sessions and mentor newer tutors.',
  },
  {
    id: 'part_time_fitness_instructor',
    title: 'Fitness Instructor',
    company: 'City Gym',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 19600,
    requiredExperience: 0,
    stress: 24,
    prestige: 18,
    coworkerCountRange: { min: 3, max: 12 },
    coworkerRoles: ['Instructor', 'Lead Instructor', 'Manager'],
    compensation: {
      tipsPerYear: 800,
      overtimeHours: 20,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['part_time_lead_instructor'],
      minYearsInRole: 1,
      minPerformance: 62,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Lead fitness classes and help members reach goals.',
  },
  {
    id: 'part_time_lead_instructor',
    title: 'Lead Fitness Instructor',
    company: 'City Gym',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 20,
    salary: 26400,
    requiredExperience: 2,
    stress: 30,
    prestige: 26,
    coworkerCountRange: { min: 5, max: 16 },
    coworkerRoles: ['Instructor', 'Lead Instructor', 'Manager'],
    compensation: {
      bonusRate: 0.06,
      tipsPerYear: 1200,
      overtimeHours: 26,
      overtimeMultiplier: 1.3,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Train other instructors and develop new class formats.',
  },
  {
    id: 'part_time_cashier',
    title: 'Cashier',
    company: 'Neighborhood Market',
    category: 'retail',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 19200,
    requiredExperience: 0,
    stress: 28,
    prestige: 10,
    coworkerCountRange: { min: 4, max: 12 },
    coworkerRoles: ['Cashier', 'Stocker', 'Shift Lead'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 18,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['part_time_grocery_clerk'],
      minYearsInRole: 0.5,
      minPerformance: 55,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Handle transactions and customer service at checkout.',
  },
  {
    id: 'part_time_waiter',
    title: 'Server',
    company: 'Corner Brew',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 18200,
    requiredExperience: 0,
    stress: 32,
    prestige: 16,
    coworkerCountRange: { min: 4, max: 14 },
    coworkerRoles: ['Server', 'Bartender', 'Shift Lead'],
    compensation: {
      tipsPerYear: 4200,
      overtimeHours: 24,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['part_time_bartender'],
      minYearsInRole: 1,
      minPerformance: 64,
    },
    jobActions: [...PART_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Serve customers and earn tips in a restaurant setting.',
  },
  {
    id: 'part_time_bartender',
    title: 'Bartender',
    company: 'Corner Brew',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 21,
    salary: 22400,
    requiredExperience: 1,
    stress: 36,
    prestige: 22,
    coworkerCountRange: { min: 5, max: 16 },
    coworkerRoles: ['Server', 'Bartender', 'Bar Manager'],
    compensation: {
      tipsPerYear: 6800,
      overtimeHours: 30,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_restaurant_manager'],
      minYearsInRole: 2,
      minPerformance: 70,
    },
    jobActions: [...PART_TIME_ACTIONS, ...BARISTA_ACTIONS],
    summary: 'Mix drinks, serve customers, and earn strong tips.',
  },
  {
    id: 'part_time_receptionist',
    title: 'Receptionist',
    company: 'City Office',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 20800,
    requiredExperience: 0,
    stress: 20,
    prestige: 20,
    coworkerCountRange: { min: 2, max: 8 },
    coworkerRoles: ['Receptionist', 'Admin Assistant', 'Office Manager'],
    compensation: {
      tipsPerYear: 0,
      overtimeHours: 14,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['part_time_admin_assistant'],
      minYearsInRole: 1,
      minPerformance: 60,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Handle front desk duties and office administration.',
  },
  {
    id: 'part_time_admin_assistant',
    title: 'Administrative Assistant',
    company: 'City Office',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 20,
    salary: 27200,
    requiredExperience: 1,
    stress: 26,
    prestige: 28,
    coworkerCountRange: { min: 3, max: 12 },
    coworkerRoles: ['Receptionist', 'Admin Assistant', 'Office Manager'],
    compensation: {
      bonusRate: 0.04,
      tipsPerYear: 0,
      overtimeHours: 20,
      overtimeMultiplier: 1.25,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Support office operations and coordinate schedules.',
  },
  {
    id: 'part_time_landscaper',
    title: 'Landscaper',
    company: 'Green Thumb Services',
    category: 'trades',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 19600,
    requiredExperience: 0,
    stress: 22,
    prestige: 12,
    coworkerCountRange: { min: 3, max: 10 },
    coworkerRoles: ['Laborer', 'Crew Lead', 'Foreman'],
    compensation: {
      tipsPerYear: 400,
      overtimeHours: 32,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['part_time_crew_lead'],
      minYearsInRole: 1,
      minPerformance: 58,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Outdoor work maintaining lawns and gardens.',
  },
  {
    id: 'part_time_crew_lead',
    title: 'Crew Lead',
    company: 'Green Thumb Services',
    category: 'trades',
    track: 'partTime',
    path: 'standard',
    minAge: 19,
    salary: 25600,
    requiredExperience: 2,
    stress: 30,
    prestige: 20,
    coworkerCountRange: { min: 5, max: 14 },
    coworkerRoles: ['Landscaper', 'Crew Lead', 'Foreman'],
    compensation: {
      bonusRate: 0.05,
      tipsPerYear: 600,
      overtimeHours: 38,
      overtimeMultiplier: 1.3,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Lead landscaping crews and coordinate job sites.',
  },
  {
    id: 'part_time_dog_walker',
    title: 'Dog Walker',
    company: 'Pet Care Services',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 16,
    salary: 16800,
    requiredExperience: 0,
    stress: 18,
    prestige: 14,
    coworkerCountRange: { min: 2, max: 8 },
    coworkerRoles: ['Walker', 'Senior Walker', 'Coordinator'],
    compensation: {
      tipsPerYear: 1200,
      overtimeHours: 16,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['part_time_pet_care_coordinator'],
      minYearsInRole: 1,
      minPerformance: 62,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Walk dogs and provide pet care services.',
  },
  {
    id: 'part_time_pet_care_coordinator',
    title: 'Pet Care Coordinator',
    company: 'Pet Care Services',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 19,
    salary: 23200,
    requiredExperience: 2,
    stress: 24,
    prestige: 22,
    coworkerCountRange: { min: 4, max: 12 },
    coworkerRoles: ['Walker', 'Coordinator', 'Manager'],
    compensation: {
      bonusRate: 0.04,
      tipsPerYear: 1800,
      overtimeHours: 22,
      overtimeMultiplier: 1.25,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Coordinate pet care schedules and manage walkers.',
  },
  {
    id: 'part_time_event_staff',
    title: 'Event Staff',
    company: 'City Events',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 18,
    salary: 19200,
    requiredExperience: 0,
    stress: 28,
    prestige: 16,
    coworkerCountRange: { min: 4, max: 16 },
    coworkerRoles: ['Staff', 'Lead Staff', 'Coordinator'],
    compensation: {
      tipsPerYear: 600,
      overtimeHours: 26,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['part_time_event_coordinator'],
      minYearsInRole: 1,
      minPerformance: 64,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Set up and staff events, concerts, and conferences.',
  },
  {
    id: 'part_time_event_coordinator',
    title: 'Event Coordinator',
    company: 'City Events',
    category: 'service',
    track: 'partTime',
    path: 'standard',
    minAge: 21,
    salary: 28800,
    requiredExperience: 2,
    stress: 34,
    prestige: 28,
    coworkerCountRange: { min: 6, max: 20 },
    coworkerRoles: ['Staff', 'Coordinator', 'Manager'],
    compensation: {
      bonusRate: 0.06,
      tipsPerYear: 1000,
      overtimeHours: 32,
      overtimeMultiplier: 1.3,
    },
    jobActions: PART_TIME_ACTIONS,
    summary: 'Coordinate event logistics and manage staff.',
  },
];
