import type { CareerDefinition } from './types';
import { FULL_TIME_ACTIONS, POLITICIAN_ACTIONS } from './actions';

export const politicianCareers: CareerDefinition[] = [
  {
    id: 'full_time_city_council_member',
    title: 'City Council Member',
    company: 'City Government',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 26,
    salary: 72000,
    requiredExperience: 3,
    stress: 58,
    prestige: 64,
    coworkerCountRange: { min: 10, max: 28 },
    coworkerRoles: ['Policy Advisor', 'Constituent Liaison', 'Legislative Aide'],
    compensation: {
      bonusRate: 0.06,
      tipsPerYear: 0,
      overtimeHours: 48,
      overtimeMultiplier: 1.2,
    },
    progression: {
      nextJobIds: ['full_time_mayor', 'full_time_state_representative'],
      minYearsInRole: 2,
      minPerformance: 72,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Represent your district and build a public service track.',
  },
  {
    id: 'full_time_mayor',
    title: 'Mayor',
    company: 'City Hall',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 30,
    salary: 118000,
    requiredExperience: 8,
    stress: 64,
    prestige: 72,
    coworkerCountRange: { min: 16, max: 36 },
    coworkerRoles: ['Chief of Staff', 'Budget Director', 'Press Secretary'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 0,
      overtimeHours: 55,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_governor', 'full_time_senator'],
      minYearsInRole: 3,
      minPerformance: 78,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Lead city policy, budget priorities, and civic outcomes.',
  },
  {
    id: 'full_time_state_representative',
    title: 'State Representative',
    company: 'State Legislature',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 30,
    salary: 136000,
    requiredExperience: 9,
    stress: 66,
    prestige: 76,
    coworkerCountRange: { min: 18, max: 42 },
    coworkerRoles: ['Legislative Counsel', 'Policy Analyst', 'District Director'],
    compensation: {
      bonusRate: 0.08,
      tipsPerYear: 0,
      overtimeHours: 58,
      overtimeMultiplier: 1.25,
    },
    progression: {
      nextJobIds: ['full_time_governor', 'full_time_senator'],
      minYearsInRole: 3,
      minPerformance: 80,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Draft bills and shape state-level policy decisions.',
  },
  {
    id: 'full_time_governor',
    title: 'Governor',
    company: 'State Executive Office',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 35,
    salary: 212000,
    requiredExperience: 13,
    stress: 72,
    prestige: 86,
    coworkerCountRange: { min: 24, max: 56 },
    coworkerRoles: ['Chief of Staff', 'Cabinet Secretary', 'Policy Director'],
    compensation: {
      bonusRate: 0.1,
      tipsPerYear: 0,
      overtimeHours: 66,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_senator', 'full_time_president'],
      minYearsInRole: 4,
      minPerformance: 84,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Run statewide administration and executive agenda.',
  },
  {
    id: 'full_time_senator',
    title: 'Senator',
    company: 'Federal Senate',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 38,
    salary: 286000,
    requiredExperience: 16,
    stress: 76,
    prestige: 92,
    coworkerCountRange: { min: 26, max: 62 },
    coworkerRoles: ['Policy Chief', 'National Security Advisor', 'Communications Director'],
    compensation: {
      bonusRate: 0.12,
      tipsPerYear: 0,
      overtimeHours: 72,
      overtimeMultiplier: 1.3,
    },
    progression: {
      nextJobIds: ['full_time_president'],
      minYearsInRole: 4,
      minPerformance: 88,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Shape federal law and national policy direction.',
  },
  {
    id: 'full_time_president',
    title: 'President',
    company: 'Executive Office',
    category: 'government',
    track: 'special',
    path: 'standard',
    advancement: 'election',
    minAge: 44,
    salary: 450000,
    requiredExperience: 22,
    stress: 86,
    prestige: 100,
    coworkerCountRange: { min: 34, max: 84 },
    coworkerRoles: ['Chief of Staff', 'Cabinet Member', 'National Advisor'],
    compensation: {
      bonusRate: 0.15,
      tipsPerYear: 0,
      overtimeHours: 82,
      overtimeMultiplier: 1.35,
    },
    jobActions: [...FULL_TIME_ACTIONS, ...POLITICIAN_ACTIONS],
    summary: 'Lead national strategy across economy, diplomacy, and law.',
  },
];
