import type { CareerDefinition } from './types';

export const soonCareers: CareerDefinition[] = [
  {
    id: 'soon_founder',
    title: 'Business Founder',
    company: 'Your Own Venture',
    category: 'finance',
    track: 'soon',
    path: 'business',
    minAge: 18,
    salary: 0,
    requiredExperience: 0,
    stress: 0,
    prestige: 0,
    coworkerCountRange: { min: 0, max: 0 },
    jobActions: [],
    summary: 'Start, fund, and scale your own company.',
    comingSoonNote: 'Will include ownership, funding rounds, and hiring systems.',
  },
  {
    id: 'soon_actor',
    title: 'Actor',
    company: 'Film and TV Industry',
    category: 'creative',
    track: 'soon',
    path: 'actor',
    minAge: 16,
    salary: 0,
    requiredExperience: 0,
    stress: 0,
    prestige: 0,
    coworkerCountRange: { min: 0, max: 0 },
    jobActions: [],
    summary: 'Auditions, representation, and role-driven fame arcs.',
    comingSoonNote: 'Will include auditions, agents, and role tiers.',
  },
  {
    id: 'soon_creator',
    title: 'Content Creator',
    company: 'Streaming Platforms',
    category: 'creative',
    track: 'soon',
    path: 'creator',
    minAge: 13,
    salary: 0,
    requiredExperience: 0,
    stress: 0,
    prestige: 0,
    coworkerCountRange: { min: 0, max: 0 },
    jobActions: [],
    summary: 'Build audience, sponsors, and platform influence.',
    comingSoonNote: 'Will include audience growth loops and sponsorship deals.',
  },
];
