import type { PlayerTraitDefinition } from './types';

export const playerTraitCatalog: PlayerTraitDefinition[] = [
  // ── Physical ──
  {
    id: 'athletic',
    label: 'Athletic',
    icon: 'fitness-outline',
    category: 'physical',
    polarity: 'positive',
    description: 'Naturally gifted in sports and physical activity.',
    effects: {
      athlete_draft: 0.25, athlete_performance: 0.15,
      military_mission: 0.15, dating_match: 0.10,
      activity_outcome_fitness: 0.20, health_decay: -0.15,
    },
  },
  {
    id: 'clumsy',
    label: 'Clumsy',
    icon: 'bandage-outline',
    category: 'physical',
    polarity: 'negative',
    description: 'Prone to accidents and physical mishaps.',
    effects: {
      athlete_draft: -0.20, athlete_performance: -0.15,
      activity_outcome_fitness: -0.15, crime_success_violent: -0.10,
      health_decay: 0.10,
    },
  },
  {
    id: 'gorgeous',
    label: 'Gorgeous',
    icon: 'sparkles-outline',
    category: 'physical',
    polarity: 'positive',
    description: 'Strikingly attractive, turning heads wherever they go.',
    effects: {
      dating_match: 0.30, dating_success: 0.15,
      fame_gain: 0.15, crime_catch: -0.15,
      career_promotion: 0.05,
    },
  },
  {
    id: 'frail',
    label: 'Frail',
    icon: 'medkit-outline',
    category: 'physical',
    polarity: 'negative',
    description: 'Physically delicate, prone to illness and injury.',
    effects: {
      health_decay: 0.25, death_chance: 0.15,
      athlete_draft: -0.30, military_mission: -0.25,
      crime_success_violent: -0.15, dating_match: -0.10,
    },
  },
  {
    id: 'tough',
    label: 'Tough',
    icon: 'shield-outline',
    category: 'physical',
    polarity: 'positive',
    description: 'Built to take a beating and keep going.',
    effects: {
      health_decay: -0.20, death_chance: -0.15,
      military_mission: 0.10, crime_success_violent: 0.10,
      athlete_performance: 0.05,
    },
  },
  {
    id: 'petite',
    label: 'Petite',
    icon: 'body-outline',
    category: 'physical',
    polarity: 'neutral',
    description: 'Smaller in stature than most.',
    effects: {
      athlete_draft: -0.10, crime_catch: -0.05,
      dating_match: 0.05,
    },
  },

  // ── Mental ──
  {
    id: 'genius',
    label: 'Genius',
    icon: 'bulb-outline',
    category: 'mental',
    polarity: 'positive',
    description: 'Exceptionally intelligent with a quick mind.',
    effects: {
      education_gpa: 0.30, education_enrollment: 0.20,
      career_promotion_tech: 0.15, career_promotion_finance: 0.15,
      crime_success_fraud: 0.20, military_asvab: 0.20,
      smarts_gain: 0.15,
    },
  },
  {
    id: 'dim',
    label: 'Dim',
    icon: 'cloud-outline',
    category: 'mental',
    polarity: 'negative',
    description: 'Struggles with complex or abstract thinking.',
    effects: {
      education_gpa: -0.30, education_enrollment: -0.20,
      career_promotion_tech: -0.15, military_asvab: -0.15,
      smarts_gain: -0.20,
    },
  },
  {
    id: 'creative',
    label: 'Creative',
    icon: 'color-palette-outline',
    category: 'mental',
    polarity: 'positive',
    description: 'A natural artist with a vivid imagination.',
    effects: {
      career_promotion_creative: 0.20,
      activity_outcome_creative: 0.20,
      fame_gain: 0.10, education_gpa: 0.05,
    },
  },
  {
    id: 'street_smart',
    label: 'Street Smart',
    icon: 'key-outline',
    category: 'mental',
    polarity: 'neutral',
    description: 'Knows how to navigate the real world.',
    effects: {
      crime_success: 0.25, crime_catch: -0.10,
      activity_push: 0.10,
      career_promotion: 0.05,
    },
  },
  {
    id: 'analytical',
    label: 'Analytical',
    icon: 'stats-chart-outline',
    category: 'mental',
    polarity: 'positive',
    description: 'Thinks in systems and patterns.',
    effects: {
      career_promotion_tech: 0.15, career_promotion_finance: 0.20,
      education_gpa: 0.10, military_mission: 0.10,
      smarts_gain: 0.10,
    },
  },
  {
    id: 'scatterbrained',
    label: 'Scatterbrained',
    icon: 'sync-outline',
    category: 'mental',
    polarity: 'negative',
    description: 'Easily distracted and forgetful.',
    effects: {
      education_gpa: -0.15, career_firing: 0.10,
      activity_outcome: -0.08, military_mission: -0.10,
    },
  },

  // ── Social ──
  {
    id: 'charismatic',
    label: 'Charismatic',
    icon: 'star-outline',
    category: 'social',
    polarity: 'positive',
    description: 'People are naturally drawn to them.',
    effects: {
      dating_match: 0.25, dating_success: 0.20,
      career_promotion: 0.10, fame_gain: 0.15,
      military_mission: 0.10,
    },
  },
  {
    id: 'awkward',
    label: 'Awkward',
    icon: 'help-circle-outline',
    category: 'social',
    polarity: 'negative',
    description: 'Socially uncomfortable and often misread.',
    effects: {
      dating_match: -0.20, dating_success: -0.15,
      career_promotion: -0.08, fame_gain: -0.10,
    },
  },
  {
    id: 'manipulative',
    label: 'Manipulative',
    icon: 'git-branch-outline',
    category: 'social',
    polarity: 'negative',
    description: 'Skilled at getting what they want from others.',
    effects: {
      crime_success_fraud: 0.15, crime_catch: -0.10,
      career_promotion: 0.08,
      dating_match: 0.10, dating_success: -0.10,
    },
  },
  {
    id: 'empathetic',
    label: 'Empathetic',
    icon: 'heart-outline',
    category: 'social',
    polarity: 'positive',
    description: 'Deeply in tune with others\' feelings.',
    effects: {
      happiness_gain: 0.15, dating_success: 0.15,
      career_promotion_healthcare: 0.15,
      fame_incident: -0.10,
    },
  },
  {
    id: 'loner',
    label: 'Loner',
    icon: 'walk-outline',
    category: 'social',
    polarity: 'neutral',
    description: 'Prefers solitude over social situations.',
    effects: {
      dating_match: -0.15, fame_gain: -0.10,
      activity_outcome_learning: 0.10,
      career_firing: -0.05,
    },
  },

  // ── Temperament ──
  {
    id: 'disciplined',
    label: 'Disciplined',
    icon: 'settings-outline',
    category: 'temperament',
    polarity: 'positive',
    description: 'Focused, reliable, and self-controlled.',
    effects: {
      career_promotion: 0.10, career_firing: -0.30,
      education_gpa: 0.15, military_mission: 0.20,
      athlete_performance: 0.10, military_asvab: 0.10,
    },
  },
  {
    id: 'hot_headed',
    label: 'Hot-Headed',
    icon: 'flame-outline',
    category: 'temperament',
    polarity: 'negative',
    description: 'Quick to anger and hard to calm down.',
    effects: {
      career_firing: 0.30, education_gpa: -0.10,
      dating_success: -0.15, crime_success_violent: 0.10,
      athlete_performance: 0.05, military_mission: -0.10,
      fame_incident: 0.15,
    },
  },
  {
    id: 'brave',
    label: 'Brave',
    icon: 'flag-outline',
    category: 'temperament',
    polarity: 'positive',
    description: 'Fearless in the face of danger.',
    effects: {
      military_mission: 0.20, crime_success: 0.10,
      athlete_performance: 0.05, career_promotion: 0.05,
      activity_push: 0.15,
    },
  },
  {
    id: 'cowardly',
    label: 'Cowardly',
    icon: 'exit-outline',
    category: 'temperament',
    polarity: 'negative',
    description: 'Avoids confrontation and risk at all costs.',
    effects: {
      military_mission: -0.20, crime_success: -0.15,
      activity_push: -0.15, career_promotion: -0.05,
    },
  },
  {
    id: 'patient',
    label: 'Patient',
    icon: 'hourglass-outline',
    category: 'temperament',
    polarity: 'positive',
    description: 'Willing to wait for the right moment.',
    effects: {
      education_gpa: 0.10, career_promotion: 0.08,
      dating_success: 0.10, happiness_gain: 0.10,
      career_firing: -0.10,
    },
  },
  {
    id: 'impulsive',
    label: 'Impulsive',
    icon: 'flash-outline',
    category: 'temperament',
    polarity: 'negative',
    description: 'Acts first, thinks later.',
    effects: {
      crime_success: -0.08, crime_catch: 0.10,
      career_firing: 0.15, education_gpa: -0.08,
      activity_push: 0.08, fame_incident: 0.10,
    },
  },
  {
    id: 'resilient',
    label: 'Resilient',
    icon: 'shield-checkmark-outline',
    category: 'temperament',
    polarity: 'positive',
    description: 'Bounces back quickly from setbacks.',
    effects: {
      health_decay: -0.10, death_chance: -0.10,
      happiness_gain: 0.10, career_firing: -0.10,
    },
  },

  // ── Dark ──
  {
    id: 'sociopath',
    label: 'Sociopath',
    icon: 'skull-outline',
    category: 'dark',
    polarity: 'negative',
    description: 'Lacks empathy and remorse. Sees people as tools.',
    effects: {
      crime_success: 0.30, crime_catch: -0.20,
      career_promotion: 0.10,
      dating_success: -0.20,
      military_mission: 0.15,
      happiness_gain: -0.15,
    },
  },
  {
    id: 'narcissist',
    label: 'Narcissist',
    icon: 'diamond-outline',
    category: 'dark',
    polarity: 'negative',
    description: 'Obsessed with their own image and status.',
    effects: {
      fame_gain: 0.20, fame_incident: 0.15,
      dating_match: 0.10, dating_success: -0.15,
      career_promotion: 0.05,
    },
  },
  {
    id: 'kleptomaniac',
    label: 'Kleptomaniac',
    icon: 'hand-left-outline',
    category: 'dark',
    polarity: 'negative',
    description: 'Can\'t resist the urge to steal.',
    effects: {
      crime_success: 0.15, crime_catch: 0.10,
      career_firing: 0.10, event_weight_crime: 0.30,
    },
  },
  {
    id: 'compulsive_liar',
    label: 'Compulsive Liar',
    icon: 'chatbox-ellipses-outline',
    category: 'dark',
    polarity: 'negative',
    description: 'Lies instinctively, even when the truth would be easier.',
    effects: {
      crime_success_fraud: 0.15, crime_catch: -0.08,
      career_firing: 0.15, dating_success: -0.15,
      career_promotion: 0.05,
    },
  },
];

export const playerTraitMap = new Map(playerTraitCatalog.map((t) => [t.id, t]));
